name: Generate PlantUML diagrams

on:
  push:
    paths:
      - 'diagrams/ER_Diagram.puml'    # sproži se, ko se spremeni .puml

jobs:
  plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Download PlantUML
        run: |
          wget https://github.com/plantuml/plantuml/releases/download/v1.2023.16/plantuml.jar \
            -O plantuml.jar

      - name: Generate PNG diagrams
        run: |
          mkdir -p diagrams/images
          java -jar plantuml.jar \
            -tpng diagrams/ER_Diagram.puml \
            -o diagrams/images

      - name: Commit images
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add diagrams/images/*.png
          git diff --staged --quiet || git commit -m "Auto-generate PlantUML diagrams"
          git push
